In [34]:
import pandas as pd
import numpy as np
import plotly.express as px

### Central Question: Given placed status, can student salary packages be predicted from academic, technical, and professional features?

In [2]:
df = pd.read_csv('raw_data.csv')
df.head(5)

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,mock_interview_score,attendance_percentage,backlogs,extracurricular_score,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day,placement_status,salary_package_lpa
0,1,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,...,72.647009,77.463863,2,63.382726,52.938240,Yes,6.7,3.6,Not Placed,0.00
1,2,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,...,61.699110,88.887600,1,73.694605,60.198856,No,4.4,2.3,Not Placed,0.00
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,87.396911,74.153265,0,63.329294,43.708803,No,8.8,5.9,Placed,11.99
3,4,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,...,58.401069,87.635955,1,47.636099,56.549154,Yes,8.1,4.4,Not Placed,0.00
4,5,20,Female,8.43,IT,Tier 3,1,4,3,65.018573,...,74.489201,79.120749,1,0.000000,67.268893,No,8.7,3.4,Placed,12.16

## Exploratory Data Analysis

In [50]:
df.shape

(100000, 26)

In [47]:
df.isna().sum().sum()
# The dataset contain no missing values

np.int64(0)

In [37]:
df['salary_package_lpa'].describe()

count    100000.000000
mean          7.252106
std           6.735132
min           0.000000
25%           0.000000
50%          11.100000
75%          13.470000
max          20.440000
Name: salary_package_lpa, dtype: float64

In [35]:
px.histogram(df, x = 'salary_package_lpa')

In [38]:
df['placement_status'].value_counts(normalize=True)

placement_status
Placed        0.54459
Not Placed    0.45541
Name: proportion, dtype: float64

In [49]:
placed_df = df[df['placement_status'] == 'Placed']
placed_df

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,mock_interview_score,attendance_percentage,backlogs,extracurricular_score,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day,placement_status,salary_package_lpa
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,87.396911,74.153265,0,63.329294,43.708803,No,8.8,5.9,Placed,11.99
4,5,20,Female,8.43,IT,Tier 3,1,4,3,65.018573,...,74.489201,79.120749,1,0.000000,67.268893,No,8.7,3.4,Placed,12.16
5,6,22,Male,7.44,CSE,Tier 2,1,5,1,49.758865,...,66.138578,82.038139,0,54.150818,69.210022,No,9.1,3.4,Placed,11.78
8,9,19,Male,8.52,Mechanical,Tier 2,2,5,0,100.000000,...,64.035703,89.884948,0,68.598878,42.647145,No,8.5,4.2,Placed,16.33
9,10,20,Female,8.07,Civil,Tier 2,2,2,2,93.421972,...,72.217117,88.901107,0,86.199176,1.371853,No,5.9,4.5,Placed,16.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99989,99990,20,Male,7.75,CSE,Tier 2,3,3,1,55.516358,...,61.817704,100.000000,1,55.177100,49.893938,No,8.9,5.0,Placed,14.93
99991,99992,23,Female,8.10,Civil,Tier 2,2,5,4,81.775079,...,80.204330,72.705861,1,42.276988,48.038799,Yes,6.8,3.2,Placed,15.67
99995,99996,21,Male,7.97,Mechanical,Tier 2,0,3,5,71.483407,...,57.738311,75.471631,0,54.399022,66.446410,Yes,8.0,4.3,Placed,14.54
99997,99998,20,Female,6.71,IT,Tier 2,2,4,4,66.691775,...,70.797752,93.115933,0,64.989215,32.733645,Yes,7.6,2.9,Placed,13.45
99999,100000,22,Female,8.58,ECE,Tier 3,1,3,2,92.146277,...,77.864288,89.919640,0,48.363818,21.166444,Yes,6.5,2.9,Placed,14.43

## Analysis, Hypothesis Testing

## Modeling